# Automatically generated by configure - do not modify
SRC_PATH=/home/yuroc/workspace/protocol/tool/afl/qemu_mode/qemu-2.10.0/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
